// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqXmb2i-yErKzTCgphdheXsXI2EJQMLY',
    appId: '1:1011152793806:ios:c508e9db1e842ced63e09f',
    messagingSenderId: '1011152793806',
    projectId: 'qampus-60056',
    storageBucket: 'qampus-60056.firebasestorage.app',
    iosBundleId: 'com.example.splashScreen',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABqXmb2i-yErKzTCgphdheXsXI2EJQMLY',
    appId: '1:1011152793806:ios:c508e9db1e842ced63e09f',
    messagingSenderId: '1011152793806',
    projectId: 'qampus-60056',
    storageBucket: 'qampus-60056.firebasestorage.app',
    iosBundleId: 'com.example.splashScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbMGHtuxM3Ygl9ZG9tQKulRRvBKEcgsFM',
    appId: '1:1011152793806:web:5cb2add56c13e31d63e09f',
    messagingSenderId: '1011152793806',
    projectId: 'qampus-60056',
    authDomain: 'qampus-60056.firebaseapp.com',
    storageBucket: 'qampus-60056.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMGHtuxM3Ygl9ZG9tQKulRRvBKEcgsFM',
    appId: '1:1011152793806:web:5cb2add56c13e31d63e09f',
    messagingSenderId: '1011152793806',
    projectId: 'qampus-60056',
    authDomain: 'qampus-60056.firebaseapp.com',
    storageBucket: 'qampus-60056.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXAHqD7BOw4CC7lkU6p6hhjxVJY2R8Uc',
    appId: '1:1011152793806:android:45df892c027728e363e09f',
    messagingSenderId: '1011152793806',
    projectId: 'qampus-60056',
    storageBucket: 'qampus-60056.firebasestorage.app',
  );
}
